package com.reedelk.runtime.properties;

/**
 * WARNING: Do not touch this file. It is autogenerated every
 * time a new build is executed.
 */
public final class Version {

    private static final String VERSION = "1.0.3-SNAPSHOT";
    private static final String GROUPID = "com.reedelk";
    private static final String ARTIFACTID = "runtime-launcher";
    private static final String QUALIFIER = "CE";

    public static String getVersion() {
        return VERSION;
    }

    public static String getGroupId() {
        return GROUPID;
    }

    public static String getArtifactId() {
        return ARTIFACTID;
    }

    public static String getQualifier() {
        return QUALIFIER;
    }

}
