package com.reedelk.runtime.api.message.content;

import com.reedelk.runtime.api.annotation.AutocompleteItem;
import com.reedelk.runtime.api.annotation.AutocompleteType;

import java.io.Serializable;

/**
 * The type refers to the type of the resolved data.
 * For example, the resolved data for StringContent is string, for ListContent is List,
 * ObjectContent is the object type and so on. The stream type refers to the data generated by the stream. For List
 * content the type is the type of the object in the List.
 * @param <Type> the type of the resolved data (not streamed).
 * @param <StreamType> the type of each element of the stream.
 */
@AutocompleteType(
        description = "A typed content contains information about the payload " +
                "which encapsulates. Information provided by type are payload type " +
                "(e.g String, Object, Collection), mime type (e.g text/plain, image/jpeg), " +
                "and the actual content data.")
public interface TypedContent<Type, StreamType> extends Serializable {

    @AutocompleteItem(
            signature = "type()",
            example = "message.content().type()",
            description = "Returns the data type of the content.")
    Class<Type> type();

    default Class<Type> getType() {
        return type();
    }

    @AutocompleteItem(
            signature = "streamType()",
            example = "message.content().streamType()",
            description = "Returns the data type of the stream generated by this content.")
    Class<StreamType> streamType();

    default Class<StreamType> getStreamType() {
        return streamType();
    }

    @AutocompleteItem(
            signature = "mimeType()",
            example = "message.content().mimeType()",
            description = "Returns the mime type of the content.")
    MimeType mimeType();

    default MimeType getMimeType() {
        return mimeType();
    }

    @AutocompleteItem(
            returnType = Object.class,
            signature = "data()",
            example = "message.content().data()",
            description = "Returns the actual data which could be could be a text, " +
                    "a byte array, a collection and so on depending on the component which generated it.")
    Type data();

    default Type getData() {
        return data();
    }

    TypedPublisher<StreamType> stream();

    default TypedPublisher<StreamType> getStream() {
        return stream();
    }

    @AutocompleteItem(
            signature = "isStream()",
            example = "message.content().isStream()",
            description = "Returns true if this message is a stream, false otherwise.")
    boolean isStream();

    /**
     * Consumes the stream payload if it has not been consumed yet. This method might be useful
     * to call before cloning the message. E.g the fork component uses this method before
     * invoking fork branches with a copy of the message.
     */
    @AutocompleteItem(
            signature = "consume()",
            example = "message.content().consume()",
            description = "Consumes the stream of this message by loading the entire " +
                    "stream content in memory.")
    void consume();
}
